# Generated by Django 4.2.1 on 2023-06-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
