# Generated by Django 4.2.1 on 2023-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_alter_team_fifa_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="titles",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
